import './post.css'

export default function Post () {
    return (
        <div className="post">
            <img className="postImg" src="https://github.com/vanderllee.png" alt="Minha imagem"/>

            <div className="postInfo">
                <div className="postCats">
                    <span className="postCat">Music</span>
                    <span className="postCat">Life</span>
                </div>

                <span className="postTitle">
                    titulo do post
                </span>
                <hr />
                <span className="postDate">
                    1 hour ago
                </span>
            </div>

            <p className="postDesc">
                Descrição do post...
                Descrição do post...
                Descrição do post...
                Descrição do post...
                Descrição do post...

                Descrição do post...
                Descrição do post...
                Descrição do post...
                Descrição do post...
                Descrição do post...

                Descrição do post...
                Descrição do post...
                Descrição do post...
                Descrição do post...
                Descrição do post...
                Descrição do post...
                Descrição do post...
                Descrição do post...
                Descrição do post...
                Descrição do post...
            </p>
        </div>
    )
}

